### ISSUE TITLE
Resolve the access control issue that looks to be preventing MPI Jobs from being run

### ISSUE THREAD

**Issue by jacek-dudek** [StatCan/openmpp#17]
Epic: #2 
Relates to: #8 

Currently getting a "Forbidden" error from the API server. It looks like we need a new role binding made so that notebook users can invoke MPI jobs.

**Comment by chuckbelisle** [comment]
Assessing this tasks as a 5 pts instead of 2 because of the learning curve related to K8 rolebindings

**Comment by jacek-dudek** [comment]
Did some reading related to roles and role bindings in kubernetes.

Figured out how to query kubernetes cluster to get the api group, resource name, and action verbs needed for mpi role.

Created Role and RoleBinding manifests and uploaded them to https://github.com/StatCan/openmpp

Figured out how interrogate active pods to find the associated service account names.

**Comment by jacek-dudek** [comment]
I may be blocked by another access control issue that prevents me from applying the mpi related role binding onto the notebook-server service account.

**Comment by Souheil-Yazji** [comment]
The kubeflow-mpijobs-edit ClusterRole is actually supposed to be deprecated with the removal of the MPI-operator kubeflow-manifest deployment. I think those resources were just not cleaned up. Instead, it's probably more correct to use the training-operator-edit/view/admin ClusterRoles, which also possess the appropriate permissions for MPI-jobs to give the permissions to the namespace-admin role. This will also enable the users to use the whole of the training operator instead of just editing MPI-jobs. Note the differences here: 

```
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - tfjobs
  - pytorchjobs
  - mxjobs
  - xgboostjobs
  - paddlejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```
vs 
```
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - mpijobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
 ```

I think there's a bug in the `kubeflow-admin` ClusterRole where these rules are meant to take place. The `mpijjobs` resources have conflicting verb definitions and it seems that the correct permissions are being over-written in the clusterrole's yaml file when pulled from the cluster, see first:
![image](https://github.com/StatCan/openmpp/assets/35379392/496a263b-11e2-4c87-9158-a02dadc9161e)
then
![image](https://github.com/StatCan/openmpp/assets/35379392/a698fff6-ae24-4290-846d-7063e55f96fb)
