### ISSUE TITLE
Research MPIJob Cleanup

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#37]
We need a convenient way to clean up MPIjobs from the cluster. 

#### Failed Jobs
We could possibly write failed job logs to a file then delete them right away.
#### Completed Jobs
Upon completion, write logs to file and then delete

**Comment by KrisWilliamson** [comment]
It is understood that this issue refers to the clean up of Kubernetes objects.
Kubernetes Garbage collection https://kubernetes.io/docs/concepts/architecture/garbage-collection/
Kubernetes automatic clean up of finished jobs https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by KrisWilliamson** [comment]
A decision is needed for this issue.
- Cleaning up the job after they finish, like proposed in the first comment, would require modifying the job launcher to clean up the jobs.
- Adding the ttlSecondsAfterFinished flag would not require the job launcher to be modified, only the template.

Given the Job launcher is being rewritten, the first option seems appropriate, however the second option is a very quick fix and utilizes K8s built in functionality and could be combined with the rewrite.

**Comment by KrisWilliamson** [comment]
After some testing, I got the following error:

`error when creating "MPIJob-.yaml": MPIJob in version "v1" cannot be handled as a MPIJob: strict decoding error: unknown field "spec.ttlSecondsAfterFinished"`

This flag was added in Kubernetes v1.21 as experimental and stable in v1.23.  The server version is: Server Version: v1.26.6`.

This may be an issue with the mpijobs implmentation.

**Comment by KrisWilliamson** [comment]
If the `ttlSecondsAfterFinished` flag is moved to the runPolicy field, it does not create an error.
```spec:
  #slotsPerWorker: Tensorflow example sets this attribute, but Pat's example template doesn't.
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 100
  mpiReplicaSpecs:
```

However it does not seem to clean up the job either.

**Comment by KrisWilliamson** [comment]
according to this web-site https://elastisys.io/compliantkubernetes/user-guide/safeguards/enforce-job-ttl/
```by default in Compliant Kubernetes, Jobs that do not explicitly set a TTL (spec.ttlSecondsAfterFinished) automatically get a TTL of 7 days.```

This needs to be tested.  


Also, the ttl flag does not explicitly set the time to clean-up, but ensure that garbage collection happens after the time has elapsed.  Garbage collection is suppose to happen every two minutes, but can be set to a longer period by the cluster  administrator, or set to another criteria, such as resources used.

**Comment by KrisWilliamson** [comment]
Also, although the flag does not cause an error, the training-operator may not implement it.  The MPI-Operator spec say this was implemented in v2, but we are still using v1 (see template), which might be another issue.

**Comment by KrisWilliamson** [comment]
Another example shows the ttl field in the completionPolicy section.

**Comment by Souheil-Yazji** [comment]
One suggestion would be to create a k8s cronjob to delete 'mpijob' resourcesolder than x date in all namespaces, ran nightly

**Comment by KrisWilliamson** [comment]
First attempt at defining a K* cron job manifest
```
apiVersion: batch/v1
kind: CronJob
metadata: 
name: mpiCleanup
namespace:  openmpp-uat
spec:
  schedule: "* 6 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - find /dir/to/log/files -mtime +6 -type f -delete
          restartPolicy: OnFailure
```

* The `schedule: "* 6 * * 0"` tells the script to run at Sunday midnight (offset 6 hours due to the server running on UTC)
* The find command finds files in a specified dir that are older than 6 days, and deletes them.

RBAC setting may be required.
